isEnabled: true
image: python:3.10-slim-bullseye
install:
  command: apt update && pip install -r requirements.txt
run:
  command: python api.py
settings:
  type: service
  security:
    type: "token"
    enableCors: true
    allowedGroups:
      - br
    useLoginFallback: true