"""Load environment variables"""
import os

AZURE_ENDPOINT: str = os.environ["AZURE_ENDPOINT"]
AZURE_OPENAI_API_KEY: str = os.environ["AZURE_OPENAI_API_KEY"]
AZURE_OPENAI_API_VERSION: str = os.environ["AZURE_OPENAI_API_VERSION"]
AZURE_OPENAI_DEPLOYMENT: str = os.environ["AZURE_OPENAI_DEPLOYMENT"]
AZURE_DEPLOYMENT: str = os.environ["AZURE_DEPLOYMENT"]
VECTOR_STORE_ADDRESS: str = os.environ["VECTOR_STORE_ADDRESS"]
VECTOR_STORE_PASSWORD: str = os.environ["VECTOR_STORE_PASSWORD"]
INDEX_NAME: str = os.environ["INDEX_NAME"]
