isEnabled: true
image:
  imageFrom: europe-west3-docker.pkg.dev/brdata-live/cloud-deploy-images/br24-suppl-comment-detector-base-image
run:
  command: /opt/venv/bin/python3.9 -m uvicorn api:APP --host 0.0.0.0 --port 3000
settings:
  type: service
  security:
    type: "token"
    enableCors: true
    allowedGroups:
      - br
    useLoginFallback: true